/*

 BACKGROUND.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\Weirdo\Desktop\Final project GB\GBmap\simpleBackground.gbr
   Plane count   : 2 plane (16 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define backgroundWidth 20
#define backgroundHeight 18
#define backgroundBank 0

extern unsigned char background[];

/* End of BACKGROUND.H */
